{{- $fullName := include "ubuntu.fullname" . -}}
{{- $volumeName := printf "%s-%s" $fullName "data" | trunc 63 | trimSuffix "-" -}}
{{- $initContainerName := printf "%s-%s" $fullName "init-data" | trunc 63 | trimSuffix "-" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ubuntu.fullname" . }}
  labels:
    {{- include "ubuntu.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "ubuntu.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "ubuntu.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: home
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "ubuntu.fullname" .) }}
        {{- else }}
          emptyDir: {}
        {{- end }}
        - name: dshm
          emptyDir:
            medium: Memory
        - name: {{$volumeName}}
          emptyDir: {}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ubuntu.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- if .Values.service.image.custom.enabled }}
          image: "{{ .Values.service.image.custom.version }}"
          {{- else }}
          image: "{{ .Values.service.image.version }}"
          {{- end }}
          command: ["/bin/sh","-c"]
          args: ["/data/{{ .Values.init.filename}} /usr/bin/tini -- /dockerstartup/startup.sh"]
          imagePullPolicy: {{ .Values.service.image.pullPolicy }}
          env:
            - name: VNC_PW
              value: {{ .Values.security.password }}
            {{- if .Values.init.personalInit }}
            - name: PERSONNAL_INIT_SCRIPT
              values: {{ .Values.init.personalInit }}
            {{- end }}      
          envFrom: 
            {{- if .Values.environment.s3 }}
            - configMapRef:
                name: {{ include "ubuntu.configMapNameS3" . }}
            {{- end }}
            {{- if .Values.environment.vault }}
            - configMapRef:
                name: {{ include "ubuntu.configMapNameVault" . }}
            {{- end }}
            {{- if .Values.environment.git }}
            - configMapRef:
                name: {{ include "ubuntu.configMapNameGit" . }}
            {{- end }}
          ports:
            - name: http
              containerPort: 6901
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /data
              name: {{$volumeName}}
            - mountPath: /dev/shm
              name: dshm
            - mountPath: /home/headless/work
              name: home
      initContainers:
        - name: standard-init
          image: "busybox"
          command: ["/bin/sh","-c"]
          args: ["wget -O /data/{{ .Values.init.filename}} {{ .Values.init.standardInit}} && chmod +x /data/{{ .Values.init.filename}}"]
          volumeMounts:
          - mountPath: /data
            name: {{$volumeName}}          
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
