{{- if .Values.environment.vault -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "utilitR.configMapNameVault" . }}
  labels:
    {{- include "utilitR.labels" . | nindent 4 }}
data:
  VAULT_ADDR: "{{ .Values.vault.url }}"
  VAULT_TOKEN: "{{ .Values.vault.token }}"
  VAULT_RELATIVE_PATH: "{{ .Values.vault.secret }}"
  VAULT_TOP_DIR: "{{ .Values.vault.directory }}"
  VAULT_MOUNT: "{{ .Values.vault.mount }}"

{{- end }}