{{- if .Values.environment.git -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "utilitR.configMapNameGit" . }}
  labels:
    {{- include "utilitR.labels" . | nindent 4 }}
data:
  GIT_USER_NAME: "{{ .Values.git.name }}"
  GIT_USER_MAIL: "{{ .Values.git.email }}"
  GIT_CREDENTIALS_CACHE_DURATION: "{{ .Values.git.cache }}"

{{- end }}