# Default values for rstudio.

rstudio:
  env:
    AWS_ACCESS_KEY_ID : "null"
    AWS_S3_ENDPOINT : "null"
    AWS_DEFAULT_REGION" : "null"
    AWS_SECRET_ACCESS_KEY" : "null"
    AWS_SESSION_TOKEN" : "null"
    AWS_EXPIRATION" : "null"
    GIT_USER_NAME": "null"
    GIT_USER_MAIL": "null"
    GIT_CREDENTIALS_CACHE_DURATION": "null"
    VAULT_ADDR": "null"
    VAULT_TOKEN": "null"
    VAULT_RELATIVE_PATH: "null"    
    VAULT_TOP_DIR: "null"
    VAULT_MOUNT: "null"
    ROOT: "TRUE"
    PASSWORD: "changeme"
  fetch:
    standardInit: "https://git.lab.sspcloud.fr/innovation/plateforme-onyxia/services-ressources/-/raw/master/onyxia-init.sh"
    personalInit: "null"

# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

image:
  repository: "inseefrlab/rstudio"
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  rstudio:
    port: 80

ingress:
  enabled: true
  tls: true
  annotations:
    kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hostname: chart-example.local
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
