apiVersion: v2
name: fastai
description: fastai is a deep learning library which provides practitioners with high-level components that can quickly and easily provide state-of-the-art results in standard deep learning domains, and provides researchers with low-level components that can be mixed and matched to build new approaches.
icon: https://minio.lab.sspcloud.fr/projet-onyxia/assets/servicesImg/fastai.png 
keyworks:
  - Python
  - Jupyter
  - GPU
  - Pytorch
  - ML
home: https://www.fast.ai/
sources: 
  - https://github.com/InseeFrLab/fastai
  - https://github.com/InseeFrLab/helm-charts-datascience/tree/master/charts/fastai
  - https://github.com/fastai/docker-containers
# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 7.0.1

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
appVersion: latest

dependencies:
  - name: library-chart
    version: 2.0.20
    repository: https://inseefrlab.github.io/helm-charts-datascience
