{{- if .Values.ingress.enabled -}}
{{- $fullName := include "library-chart.fullname" . -}}
{{- $svcPortUI := .Values.networking.neo4jUI.port -}}
{{- $svcPortBolt := .Values.networking.neo4jBolt.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "library-chart.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.ingress.hostnameUI | quote }}
        - {{ .Values.ingress.hostnameBolt | quote }}
{{- end }}
  rules:
    - host: {{ .Values.ingress.hostnameUI | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPortUI }}
    - host: {{ .Values.ingress.hostnameBolt | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port: 
                  number: {{ $svcPortBolt }}
{{- end }}